# Generated by Django 2.2.3 on 2019-07-14 13:34

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """ Add Theater Rooms """
    TheaterRoom = apps.get_model("main", "TheaterRoom")
    db_alias = schema_editor.connection.alias
    TheaterRoom.objects.using(db_alias).bulk_create([
        TheaterRoom(name="Red Room", rows_count=10, seats_per_row_count=15),
        TheaterRoom(name="Blue Room", rows_count=20, seats_per_row_count=30),
    ])


def reverse_func(apps, schema_editor):
    """ No need to do anything since the table is dropped completely """
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rows_count', models.IntegerField()),
                ('seats_per_row_count', models.IntegerField()),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
