# Generated by Django 2.2.3 on 2019-07-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190714_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TheaterRoom')),
            ],
        ),
    ]
