# Generated by Django 2.2.3 on 2019-07-16 16:59

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """ Add Theater Rooms """
    Seat = apps.get_model("main", "Seat")
    TheaterRoom = apps.get_model("main", "TheaterRoom")
    db_alias = schema_editor.connection.alias
    for room in TheaterRoom.objects.all():
        Seat.objects.using(db_alias).bulk_create(
            [
                Seat(room=room, row=r + 1, number=n + 1)
                for r in range(room.rows_count)
                for n in range(room.seats_per_row_count)
            ]
        )


def reverse_func(apps, schema_editor):
    """ No need to do anything since the table is dropped completely """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_screening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TheaterRoom')),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
