# Generated by Django 2.2.3 on 2019-07-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField()),
                ('purchase_time', models.DateTimeField()),
                ('price_paid', models.IntegerField()),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
